name: Build EXE
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install Poetry
        run: |
          pip install poetry
          echo "$(pip show poetry | grep Location | awk '{print $2}')/Scripts" >> $GITHUB_ENV

      - name: Verify Poetry installation
        run: poetry --version

      - name: Install dependencies
        run: |
          poetry install
          pip install html2text==2024.2.26
          pip install pre-commit==4.0.1
          pip install pydantic==2.10.1
          pip install wxpython==4.2.2
          pip install pyinstaller
          pip install typing_extensions

      - name: Build EXE
        run: pyinstaller --onefile --noconsole src/main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: exe
          path: dist/
